apiVersion: v1
kind: Service
metadata:
  name: todo-deployment
spec:
  type: NodePort 
  selector:
    app: reactapp
  ports:
    - protocol: TCP
      port: 8000
      #targetPort: 6200
      nodePort: 33100